spring.application.name=boardinghouse
server.port=8080
spring.datasource.url=jdbc:postgresql://ep-misty-violet-aor9g96m-pooler.c-2.ap-southeast-1.aws.neon.tech/boarding_house?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_UErmiMod7Py2
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Cloudinary Configuration (Please replace with your actual keys)
cloudinary.cloud-name=dbwy4uh6d
cloudinary.api-key=163153865159965
cloudinary.api-secret=np5FjCZarAicvzFvJO1n-GsSV7c

# Suppress Hibernate harmless index and constraint warnings at startup
logging.level.org.hibernate.orm.core=WARN
logging.level.org.hibernate.orm.jdbc.warn=ERROR
